### ISSUE TITLE
HTTP POST with json payload and empty response

### ISSUE THREAD

**Issue by ricott** [matjaz/node-http.min#22]
Thanks for the minimal http client, use it in several projects of mine :)

Stumbled upon a problem this evening, and wonder if I'm doing something wrong. 
I use `http.post(options)` with `options.json = data;` and the service I invoke returns HTTP status 200 but an empty response. It seems this use case is not working properly, I get an error unable to parse json.

I now fiddled a bit with the code and see if I check for empty string in `result.data` in `parseJSON` method it works. Would this make sense to support as a use case? If `result.data` is empty return empty json `{}` as `result.data`.

**Comment by matjaz** [comment]
Added support returning empty object on empty response in https://github.com/matjaz/node-http.min/releases/tag/v2.1.0
