### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by oh2th** [matjaz/node-http.min#24]
Every now and then an API returns garbage instead of the expected JSON.

Could the parseJSON first verify that it actually is parseable instead of getting a SyntaxError from JSON.parse()?

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse ()
    at parseJSON (/app/node_modules/http.min/index.js:106:24)
    at IncomingMessage. (/app/node_modules/http.min/index.js:60:22)
    at IncomingMessage.emit (node:events:529:35)
    at IncomingMessage.emit (node:domain:489:12)

**Comment by matjaz** [comment]
Can you provide an example?

Invalid JSON is covered by this test. https://github.com/matjaz/node-http.min/blob/bb29b81b278427db0af619cc76eccd9a35266108/test/index.js#L265

I am not fond of checking response content. We could check content-type header.

**Comment by oh2th** [comment]
Found what the issue is, the upstream API returns HTML page while there was Backend server error. Adding now check for result.response.statusCode. So it should be fine. Just so surprised that the API fails so often, and that is not in my hands.

This case can be closed.
