### ISSUE TITLE
Consider ability to set a timeout

### ISSUE THREAD

**Issue by hunterloftis** [matjaz/node-http.min#5]
Lovely little library! It would be fantastic to be able to set a timeout for requests, which currently is impossible (no way to call `request.setTimeout` since the request instance is not returned to the user).

**Comment by matjaz** [comment]
`options.timeout: ms` would be obvious, but what about other `ClientRequest` methods?
Maybe something like
```
http.get({
    ...
    request: (request) {
        request.setTimeout...
    }
})
```
With this, user can also hook into events.

Thanks!

**Comment by hunterloftis** [comment]
A hook that passes the request instance sounds like a great solution to me.
